spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        types:
          print:
            banner: false
  datasource:
    driverClassName: org.postgresql.Driver
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/db
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

config:
  s3:
    endpoint: http://localhost:9000
    accessKey: admin
    secretKey: adminadmin
    region: us-east-1
    auto: false

logging:
  level:
    liquidbase: INFO

server:
  port: 8888