spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/db
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

logging:
  level:
    liquidbase: INFO

server:
  port: 8888